# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  test:
    docker:
      # specify the version you desire here
      - image: maven:3.8.2-openjdk-16
    steps:
    - checkout
    - run: 
        name: Maven Test
        command: mvn test

  build:
    docker:
      # specify the version you desire here
      - image: maven:3.8.2-openjdk-16

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4


    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - run: 
         name: Maven Build
         command: mvn clean compile assembly:single
      - store_artifacts: # Upload test results for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: target/volga-1.0-SNAPSHOT-jar-with-dependencies.jar